### ISSUE TITLE
Access Roles

### ISSUE THREAD

**Issue by mwitiderrick** [WorldChangers/v1_isurex#16]
The system should have different users with different permissions. The super admin has all the rights. Normal users have right to read and add items. Some sections of the system(TBD) may also be restricted to users with admin rights

**Comment by thedma04** [comment]
Have that already
But as to which right to adhere to is what is missing
Besides we are not building a dashboard for admin yet

![image](https://user-images.githubusercontent.com/11330782/36933740-438aff94-1ed6-11e8-8f57-044690571254.png)
